set(CMAKE_SYSTEM_NAME WASI)
set(CMAKE_SYSTEM_PROCESSOR wasm32)

set(CMAKE_C_COMPILER wasixcc)
set(CMAKE_CXX_COMPILER wasixcc++)
set(CMAKE_AR wasixar)
set(CMAKE_RANLIB wasixranlib)

set(CMAKE_C_COMPILER_TARGET wasm32-wasix)
set(CMAKE_CXX_COMPILER_TARGET wasm32-wasix)

set(CMAKE_C_FLAGS_INIT "--target=wasm32-wasix")
set(CMAKE_CXX_FLAGS_INIT "--target=wasm32-wasix")
set(CMAKE_EXE_LINKER_FLAGS_INIT "-Wl,--allow-undefined")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
